In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('data/reference/lopucki_brd_2023.csv', encoding='latin-1', on_bad_lines='skip')
df.head()

,NameCorp,AfterEmerging,Assets1Before,Assets2Before,Assets3Before,AssetsBefore,AssetsCurrDollar,AssetsEmerging,AssetsPetCurrDollar,AssetsPetition,...,TurnPerson,TurnRepRange,TurnType,UsPopFiling,Voluntary,YearConfirmed,YearDisposed,YearEmerged,YearFiled,YearsEmergeToRefile
0,1st Centennial Bancorp,NaN,NaN,690.000,NaN,690.000,963,NaN,NaN,NaN,...,NaN,NaN,NaN,306770000,voluntary,NaN,NaN,NaN,2009,NaN
1,"21st Century Oncology Holdings, Inc.",NaN,NaN,1128.244,NaN,1128.244,1368,NaN,NaN,NaN,...,NaN,NaN,NaN,325719178,voluntary,2018.0,2018.0,2018.0,2017,NaN
2,"A. H. Robins Company, Inc.",Became a unit of American Home Products 12/15/89,648.000,509.663,439.983,648.000,1781,NaN,1281.0,466.000,...,NaN,NaN,NaN,237920000,voluntary,1988.0,1988.0,1988.0,1985,NaN
3,A. M. Castle & Co.,NaN,329.328,NaN,NaN,329.328,399,332.285,NaN,NaN,...,NaN,NaN,NaN,325719178,voluntary,2017.0,2017.0,2017.0,2017,NaN
4,"A123 Systems, Inc.",assets acquired by Wanxiang America Corporatio...,625.902,NaN,NaN,625.902,803,NaN,590.0,459.795,...,none,NaN,none,313910000,voluntary,2013.0,2013.0,2012.0,2012,NaN

In [8]:
df['CikEmerging'].value_counts()

CikEmerging
1282648.0    2
906469.0     2
19411.0      2
943320.0     2
850660.0     2
            ..
1467858.0    1
1443799.0    1
1496048.0    1
771934.0     1
109265.0     1
Name: count, Length: 358, dtype: int64

In [7]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 217 columns):
 #    Column                 Non-Null Count  Dtype
---   ------                 --------------  -----
 0    NameCorp               1218 non-null   object
 1    AfterEmerging          549 non-null    object
 2    Assets1Before          913 non-null    float64
 3    Assets2Before          546 non-null    float64
 4    Assets3Before          318 non-null    float64
 5    AssetsBefore           1218 non-null   float64
 6    AssetsCurrDollar       1218 non-null   int64
 7    AssetsEmerging         429 non-null    float64
 8    AssetsPetCurrDollar    883 non-null    float64
 9    AssetsPetition         883 non-null    float64
 10   BondISIN               217 non-null    object
 11   BondPriceDisp          161 non-null    float64
 12   BondPriceFile          161 non-null    float64
 13   BondPriceMoveDuring    151 non-null    float64
 14   CaseNum                1218 non-null   object
 15   CaseNumRefile          173 non-null    object
 16   CaseNumTransfer        28 non-null     object
 17   CeoFiling              1218 non-null   object
 18   CeoNotes               412 non-null    object
 19   CeoReplaced            1218 non-null   object
 20   Chapter                1218 non-null   object
 21   CikBefore              992 non-null    float64
 22   CikEmerging            369 non-null    float64
 23   CityChange             44 non-null     object
 24   CityDisposed           1169 non-null   object
 25   CityFiled              1218 non-null   object
 26   CityFiledCategory      1218 non-null   object
 27   CityRefile             173 non-null    object
 28   ClaimsAgent            523 non-null    object
 29   ClaimsAgentFirm        500 non-null    object
 30   ClaimsSecDiscloState   119 non-null    float64
 31   ClaimsUnsec            129 non-null    float64
 32   CommCred               1218 non-null   object
 33   CommCredAtty           775 non-null    object
 34   CommCredAttyCol        802 non-null    object
 35   CommCredAttySubstit    7 non-null      object
 36   CommEquity             1218 non-null   object
 37   CommEquityAtty         50 non-null     object
 38   CommEquityAttyCol      50 non-null     object
 39   CommEquityAttySubstit  2 non-null      object
 40   CommRetirees           1045 non-null   object
 41   CommRetireesName       39 non-null     object
 42   CommRetireesRequest    43 non-null     object
 43   CommonName             112 non-null    object
 44   CPIndexAtConf          1095 non-null   float64
 45   CPIndexAtFiling        1218 non-null   float64
 46   Cusip6                 1213 non-null   object
 47   Cusip9                 1140 non-null   object
 48   Date10k1Before         913 non-null    object
 49   Date10k2Before         543 non-null    object
 50   Date10k3Before         332 non-null    object
 51   Date10kBefore          1218 non-null   object
 52   Date10kBeforeLink      968 non-null    object
 53   Date10kDuring          159 non-null    object
 54   Date10kDuringLink      159 non-null    object
 55   Date10kEmerging        448 non-null    object
 56   Date10kEmergLink       305 non-null    object
 57   Date10kSalesEmerge     393 non-null    object
 58   Date363Sale            204 non-null    object
 59   DateCeoBegin           1189 non-null   object
 60   DateCeoEnd             1170 non-null   object
 61   DateCommCred           870 non-null    object
 62   DateCommCredBy         39 non-null     object
 63   DateConfirmed          1095 non-null   object
 64   DateConvDismiss        89 non-null     object
 65   DateDipLoan1FinOrd     545 non-null    object
 66   DateDiscloState        866 non-null    object
 67   DateDisposed           1182 non-null   object
 68   DateEffective          958 non-null    object
 69   DateEmerging           817 non-null    object
 70   DateFeeRev             90 non-null     object
 71   DateFiled              1218 non-null   object
 72   DateJudgeAppt          1186 non-null   object
 73   DateRefile             173 non-null    object
 74   DateTransferred        26 non-null     object
 75   DateTurnEngage         149 non-null    object
 76   DaysDocsAfter          206 non-null    float64
 77   DaysFiledTo363         206 non-null    float64
 78   DaysEmergeToRefile     173 non-null    float64
 79   DaysIn                 1182 non-null   float64
 80   DENYOther              1218 non-null   object
 81   DipAtty                1217 non-null   object
 82   DipAttyColDoc          1041 non-null   object
 83   DipAttyColDkt          176 non-null    object
 84   DipFinAdvPetition      157 non-null    object
 85   DipLoan1Lender         343 non-null    object
 86   DipLoan1Total          349 non-null    float64
 87   DipLoan2Lender         39 non-null     object
 88   DipLoan2Total          39 non-null     float64
 89   DipLoanAdditional      4 non-null      object
 90   DipLoanDoc             686 non-null    object
 91   DipLoan                1034 non-null   object
 92   Disposition            1218 non-null   object
 93   DistFiled              1218 non-null   object
 94   DistribComments        15 non-null     object
 95   DistribEquity          128 non-null    float64
 96   DistribSecDiscloState  119 non-null    float64
 97   DistribUnsec           129 non-null    float64
 98   DistribUnsecPct        129 non-null    float64
 99   DktNumConf             930 non-null    float64
 100  DktOnPacer             1218 non-null   object
 101  DocsOnPacer            1218 non-null   object
 102  DocsPublic             1218 non-null   object
 103  EbitBefore             1189 non-null   float64
 104  EbitCurrDollars        1189 non-null   float64
 105  EbitdaBefore           1104 non-null   float64
 106  EbitdaEmerging         380 non-null    float64
 107  EbitEmerging           388 non-null    float64
 108  Emerge                 1218 non-null   object
 109  Emerg10k               1218 non-null   object
 110  EmplBefore             1215 non-null   float64
 111  EmplEmerging           428 non-null    float64
 112  EmplUnionBefore        1029 non-null   float64
 113  EmplUnionEmerging      343 non-null    float64
 114  Examiner               981 non-null    object
 115  ExaminerName           54 non-null     object
 116  ExaminerRequest        945 non-null    object
 117  FeeReviewer            1218 non-null   object
 118  FilingRate             1218 non-null   int64
 119  FirmEnd                71 non-null     object
 120  FreshStartAccounting   356 non-null    object
 121  GdpDisp                1180 non-null   float64
 122  GdpFiling              1217 non-null   float64
 123  GdpRefiling            173 non-null    float64
 124  GdpYear1AftDisp        1176 non-null   float64
 125  GdpYear1BefFile        1218 non-null   float64
 126  GdpYear2AftDisp        1137 non-null   float64
 127  GdpYear2BefFile        1218 non-null   float64
 128  GvkeyBefore            1218 non-null   int64
 129  GvkeyEmerging          447 non-null    float64
 130  HeadCAtFiling          1218 non-null   object
 131  HeadCityPctPop         1218 non-null   float64
 132  HeadCityPop            1218 non-null   float64
 133  HeadCourtCity          1218 non-null   object
 134  HeadCourtCityToDE      1189 non-null   float64
 135  HeadStAtFiling         1218 non-null   object
 136  HqToForum              1218 non-null   int64
 137  HqToHqCtCity           1189 non-null   float64
 138  IncomeBEBefore         1122 non-null   float64
 139  IncomeBEEmerging       389 non-null    float64
 140  IncPublic              1218 non-null   object
 141  InterCompanyClaims     75 non-null     object
 142  InterCompanyPct        50 non-null     float64
 143  InterCompanyDistrib    62 non-null     object
 144  JudgeApptDist          1186 non-null   object
 145  JudgeDisposition       1211 non-null   object
 146  JudgeFiling            1041 non-null   object
 147  Liab1Before            889 non-null    float64
 148  Liab2Before            427 non-null    float64
 149  Liab3Before            108 non-null    float64
 150  LiabBefore             1199 non-null   float64
 151  LiabCurrDollar         1199 non-null   float64
 152  LiabEmerging           427 non-null    float64
 153  LiabPetCurrDollar      658 non-null    float64
 154  LiabPetition           658 non-null    float64
 155  MonthDisp              1182 non-null   float64
 156  MonthFiled             1218 non-null   int64
 157  MonthRefile            173 non-null    float64
 158  MonthsIn               1182 non-null   float64
 159  Multiple363Sales       60 non-null     object
 160  NameEmerging           1218 non-null   object
 161  NetIncomeBefore        1122 non-null   float64
 162  NetIncomeEmerging      389 non-null    float64
 163  NumberFiling           789 non-null    float64
 164  Prepackaged            1218 non-null   object
 165  PrimaryKey             1218 non-null   int64
 166  Prime1YearAftDisp      1177 non-null   float64
 167  Prime1YearBefFile      1218 non-null   float64
 168  Prime2YearAftDisp      1158 non-null   float64
 169  Prime2YearBefFile      1218 non-null   float64
 170  PrimeDisp              1182 non-null   float64
 171  PrimeFiling            1218 non-null   float64
 172  PrimeRefiling          173 non-null    float64
 173  ProfFees10k            151 non-null    float64
 174  ProfFees10kNotes       499 non-null    object
 175  Refile                 173 non-null    object
 176  Refile5                1218 non-null   object
 177  Refile5RepRange        1218 non-null   object
 178  RelatedFilings         87 non-null     object
 179  Sale                   1159 non-null   object
 180  Sale363                1218 non-null   object
 181  SaleConf               933 non-null    object
 182  SaleIntended           1008 non-null   object
 183  Sales1Before           933 non-null    float64
 184  Sales2Before           569 non-null    float64
 185  Sales3Before           399 non-null    float64
 186  SalesBefore            1217 non-null   float64
 187  SalesCurrDollar        1217 non-null   float64
 188  SalesEmerging          363 non-null    float64
 189  Shop                   1218 non-null   object
 190  SICDescription         975 non-null    object
 191  SICDivision            1218 non-null   object
 192  SICIndustryGroup       1145 non-null   object
 193  SICMajGroup            1218 non-null   object
 194  SICPrimary             1218 non-null   int64
 195  SubCon                 75 non-null     object
 196  TortCause              1218 non-null   object
 197  TransferCity           29 non-null     object
 198  TransferDist           28 non-null     object
 199  Transferred            1203 non-null   object
 200  Trustee                804 non-null    object
 201  TrusteeFor             33 non-null     object
 202  TrusteeName            26 non-null     object
 203  TrusteeRequest         717 non-null    object
 204  TrusteeRequestor       717 non-null    object
 205  TurnFirm               308 non-null    object
 206  TurnOffice             282 non-null    object
 207  TurnPerson             282 non-null    object
 208  TurnRepRange           264 non-null    object
 209  TurnType               282 non-null    object
 210  UsPopFiling            1218 non-null   int64
 211  Voluntary              1218 non-null   object
 212  YearConfirmed          1096 non-null   float64
 213  YearDisposed           1182 non-null   float64
 214  YearEmerged            817 non-null    float64
 215  YearFiled              1218 non-null   int64
 216  YearsEmergeToRefile    173 non-null    float64
dtypes: float64(83), int64(9), object(125)
memory usage: 2.0+ MB

In [18]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [20]:
df.select_dtypes(include=['object']).info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 125 columns):
 #    Column                 Non-Null Count  Dtype
---   ------                 --------------  -----
 0    NameCorp               1218 non-null   object
 1    AfterEmerging          549 non-null    object
 2    BondISIN               217 non-null    object
 3    CaseNum                1218 non-null   object
 4    CaseNumRefile          173 non-null    object
 5    CaseNumTransfer        28 non-null     object
 6    CeoFiling              1218 non-null   object
 7    CeoNotes               412 non-null    object
 8    CeoReplaced            1218 non-null   object
 9    Chapter                1218 non-null   object
 10   CityChange             44 non-null     object
 11   CityDisposed           1169 non-null   object
 12   CityFiled              1218 non-null   object
 13   CityFiledCategory      1218 non-null   object
 14   CityRefile             173 non-null    object
 15   ClaimsAgent            523 non-null    object
 16   ClaimsAgentFirm        500 non-null    object
 17   CommCred               1218 non-null   object
 18   CommCredAtty           775 non-null    object
 19   CommCredAttyCol        802 non-null    object
 20   CommCredAttySubstit    7 non-null      object
 21   CommEquity             1218 non-null   object
 22   CommEquityAtty         50 non-null     object
 23   CommEquityAttyCol      50 non-null     object
 24   CommEquityAttySubstit  2 non-null      object
 25   CommRetirees           1045 non-null   object
 26   CommRetireesName       39 non-null     object
 27   CommRetireesRequest    43 non-null     object
 28   CommonName             112 non-null    object
 29   Cusip6                 1213 non-null   object
 30   Cusip9                 1140 non-null   object
 31   Date10k1Before         913 non-null    object
 32   Date10k2Before         543 non-null    object
 33   Date10k3Before         332 non-null    object
 34   Date10kBefore          1218 non-null   object
 35   Date10kBeforeLink      968 non-null    object
 36   Date10kDuring          159 non-null    object
 37   Date10kDuringLink      159 non-null    object
 38   Date10kEmerging        448 non-null    object
 39   Date10kEmergLink       305 non-null    object
 40   Date10kSalesEmerge     393 non-null    object
 41   Date363Sale            204 non-null    object
 42   DateCeoBegin           1189 non-null   object
 43   DateCeoEnd             1170 non-null   object
 44   DateCommCred           870 non-null    object
 45   DateCommCredBy         39 non-null     object
 46   DateConfirmed          1095 non-null   object
 47   DateConvDismiss        89 non-null     object
 48   DateDipLoan1FinOrd     545 non-null    object
 49   DateDiscloState        866 non-null    object
 50   DateDisposed           1182 non-null   object
 51   DateEffective          958 non-null    object
 52   DateEmerging           817 non-null    object
 53   DateFeeRev             90 non-null     object
 54   DateFiled              1218 non-null   object
 55   DateJudgeAppt          1186 non-null   object
 56   DateRefile             173 non-null    object
 57   DateTransferred        26 non-null     object
 58   DateTurnEngage         149 non-null    object
 59   DENYOther              1218 non-null   object
 60   DipAtty                1217 non-null   object
 61   DipAttyColDoc          1041 non-null   object
 62   DipAttyColDkt          176 non-null    object
 63   DipFinAdvPetition      157 non-null    object
 64   DipLoan1Lender         343 non-null    object
 65   DipLoan2Lender         39 non-null     object
 66   DipLoanAdditional      4 non-null      object
 67   DipLoanDoc             686 non-null    object
 68   DipLoan                1034 non-null   object
 69   Disposition            1218 non-null   object
 70   DistFiled              1218 non-null   object
 71   DistribComments        15 non-null     object
 72   DktOnPacer             1218 non-null   object
 73   DocsOnPacer            1218 non-null   object
 74   DocsPublic             1218 non-null   object
 75   Emerge                 1218 non-null   object
 76   Emerg10k               1218 non-null   object
 77   Examiner               981 non-null    object
 78   ExaminerName           54 non-null     object
 79   ExaminerRequest        945 non-null    object
 80   FeeReviewer            1218 non-null   object
 81   FirmEnd                71 non-null     object
 82   FreshStartAccounting   356 non-null    object
 83   HeadCAtFiling          1218 non-null   object
 84   HeadCourtCity          1218 non-null   object
 85   HeadStAtFiling         1218 non-null   object
 86   IncPublic              1218 non-null   object
 87   InterCompanyClaims     75 non-null     object
 88   InterCompanyDistrib    62 non-null     object
 89   JudgeApptDist          1186 non-null   object
 90   JudgeDisposition       1211 non-null   object
 91   JudgeFiling            1041 non-null   object
 92   Multiple363Sales       60 non-null     object
 93   NameEmerging           1218 non-null   object
 94   Prepackaged            1218 non-null   object
 95   ProfFees10kNotes       499 non-null    object
 96   Refile                 173 non-null    object
 97   Refile5                1218 non-null   object
 98   Refile5RepRange        1218 non-null   object
 99   RelatedFilings         87 non-null     object
 100  Sale                   1159 non-null   object
 101  Sale363                1218 non-null   object
 102  SaleConf               933 non-null    object
 103  SaleIntended           1008 non-null   object
 104  Shop                   1218 non-null   object
 105  SICDescription         975 non-null    object
 106  SICDivision            1218 non-null   object
 107  SICIndustryGroup       1145 non-null   object
 108  SICMajGroup            1218 non-null   object
 109  SubCon                 75 non-null     object
 110  TortCause              1218 non-null   object
 111  TransferCity           29 non-null     object
 112  TransferDist           28 non-null     object
 113  Transferred            1203 non-null   object
 114  Trustee                804 non-null    object
 115  TrusteeFor             33 non-null     object
 116  TrusteeName            26 non-null     object
 117  TrusteeRequest         717 non-null    object
 118  TrusteeRequestor       717 non-null    object
 119  TurnFirm               308 non-null    object
 120  TurnOffice             282 non-null    object
 121  TurnPerson             282 non-null    object
 122  TurnRepRange           264 non-null    object
 123  TurnType               282 non-null    object
 124  Voluntary              1218 non-null   object
dtypes: object(125)
memory usage: 1.2+ MB

In [19]:
df.select_dtypes(include=['object']).head(20)

,NameCorp,AfterEmerging,BondISIN,CaseNum,CaseNumRefile,CaseNumTransfer,CeoFiling,CeoNotes,CeoReplaced,Chapter,CityChange,CityDisposed,CityFiled,CityFiledCategory,CityRefile,ClaimsAgent,ClaimsAgentFirm,CommCred,CommCredAtty,CommCredAttyCol,CommCredAttySubstit,CommEquity,CommEquityAtty,CommEquityAttyCol,CommEquityAttySubstit,CommRetirees,CommRetireesName,CommRetireesRequest,CommonName,Cusip6,Cusip9,Date10k1Before,Date10k2Before,Date10k3Before,Date10kBefore,Date10kBeforeLink,Date10kDuring,Date10kDuringLink,Date10kEmerging,Date10kEmergLink,Date10kSalesEmerge,Date363Sale,DateCeoBegin,DateCeoEnd,DateCommCred,DateCommCredBy,DateConfirmed,DateConvDismiss,DateDipLoan1FinOrd,DateDiscloState,DateDisposed,DateEffective,DateEmerging,DateFeeRev,DateFiled,DateJudgeAppt,DateRefile,DateTransferred,DateTurnEngage,DENYOther,DipAtty,DipAttyColDoc,DipAttyColDkt,DipFinAdvPetition,DipLoan1Lender,DipLoan2Lender,DipLoanAdditional,DipLoanDoc,DipLoan,Disposition,DistFiled,DistribComments,DktOnPacer,DocsOnPacer,DocsPublic,Emerge,Emerg10k,Examiner,ExaminerName,ExaminerRequest,FeeReviewer,FirmEnd,FreshStartAccounting,HeadCAtFiling,HeadCourtCity,HeadStAtFiling,IncPublic,InterCompanyClaims,InterCompanyDistrib,JudgeApptDist,JudgeDisposition,JudgeFiling,Multiple363Sales,NameEmerging,Prepackaged,ProfFees10kNotes,Refile,Refile5,Refile5RepRange,RelatedFilings,Sale,Sale363,SaleConf,SaleIntended,Shop,SICDescription,SICDivision,SICIndustryGroup,SICMajGroup,SubCon,TortCause,TransferCity,TransferDist,Transferred,Trustee,TrusteeFor,TrusteeName,TrusteeRequest,TrusteeRequestor,TurnFirm,TurnOffice,TurnPerson,TurnRepRange,TurnType,Voluntary
0,1st Centennial Bancorp,NaN,NaN,09-15570,NaN,NaN,"Beth Sanders, CFO",Chapter 7 at filing,NoReplace,7,NaN,NaN,Riverside,Other,NaN,NaN,NaN,Chapter 7 at filing,NaN,NaN,NaN,Chapter 7 at filing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31986N,102,NaN,12/31/2007,NaN,12/31/2007,10/31/2007#http://edgar.sec.gov/Archives/edgar/data/1097081/000119312508050319/0001193125-08-050319-index.htm#,NaN,NaN,NaN,NaN,NaN,NaN,1/28/2009,3/25/2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3/25/2009,NaN,NaN,NaN,NaN,OT,Reid Hellyer,Reid & Hellyer,NaN,NaN,NaN,NaN,NaN,not applicable,Chapter 7 at filing,Chapter 7 at filing,CA CD,NaN,yes,yes,yes,no,no,NaN,NaN,NaN,pending,NaN,NaN,Redlands,CA Riverside,CA,CA,NaN,NaN,NaN,Chapter 7 at filing,Sheri Bluebond,NaN,Chapter 7 at filing,not applicable,NaN,NaN,not emerged 5,no,NaN,Chapter 7 at filing,Chapter 7 at filing,NaN,yes,No,State Commercial Banks,"H: Finance, Insurance, And Real Estate",602 Commercial Banks,60 Depository Institutions,NaN,Not tort,NaN,NaN,Chapter 7 at filing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,voluntary
1,"21st Century Oncology Holdings, Inc.",NaN,NaN,17-22770,NaN,NaN,Paul Rundell,Interim CEO,Replaced,11,NaN,White Plains,White Plains,White Plains,NaN,yes,Kurtzman Carson Consultants LLC,yes,Morrison Foerster,Morrison & Foerster LLP,NaN,no,NaN,NaN,NaN,no,NaN,NaN,NaN,90131G,107,NaN,12/31/2015,NaN,12/31/2015,12/31/2015#https://www.sec.gov/Archives/edgar/data/1503518/000104746916015101/0001047469-16-015101-index.htm#,NaN,NaN,NaN,NaN,NaN,NaN,3/1/2017,1/16/2018,6/15/2017,NaN,1/11/2018,NaN,6/20/2017,10/13/2017,1/11/2018,1/16/2018,1/11/2018,NaN,5/25/2017,5/24/2002,NaN,NaN,NaN,OT,Kirkland Ellis,Kirkland & Ellis LLP / Kirkland & Ellis International LLP,NaN,NaN,"Wilmington Savings Fund Society, FSB; Morgan Stanley Senior Funding, Inc.",NaN,NaN,yes,yes,confirmed,NY SD,NaN,yes,yes,yes,yes,no,no,NaN,no,pending,NaN,NaN,Fort Myers,FL Fort Myers,FL,DE,NaN,NaN,NY SD,Robert D. Drain,Robert D. Drain,NaN,"21st Century Oncology Holdings, Inc.",prenegotiated,NaN,NaN,not emerged 5,no,NaN,yes,no,yes,no,Yes,Offices and Clinics of Doctors of Medicine,I: Services,801 Offices And Clinics Of Doctors Of Medicine,80 Health Services,NaN,Not tort,NaN,NaN,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,voluntary
2,"A. H. Robins Company, Inc.",Became a unit of American Home Products 12/15/89,NaN,85-01307,NaN,NaN,E. Claiborne Robins Jr.,End day is approximate,NoReplace,11,NaN,Richmond,Richmond,Richmond,NaN,NaN,NaN,yes,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,770706,109,12/31/1984,12/31/1983,12/31/1982,12/31/1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1/1/1978,12/15/1989,9/4/1985,NaN,7/25/1988,NaN,NaN,NaN,7/25/1988,NaN,7/25/1988,NaN,8/21/1985,7/1/1967,NaN,NaN,NaN,OT,Murphy Sheneman,"Murphy, Weir & Butler",NaN,NaN,NaN,NaN,NaN,NaN,NaN,confirmed,VA ED,NaN,none,none,no,yes,no,NaN,NaN,NaN,no data,merged,NaN,Richmond,VA Richmond,VA,VA,NaN,NaN,VA ED,Robert R. Merhige,NaN,NaN,A.H. Robins,free fall,NaN,NaN,emerged no refile 5,yes,no,yes,no,yes,NaN,No,Pharmaceutical Preparations,D: Manufacturing,283 Drugs,28 Chemicals and Allied Products,NaN,Other products,NaN,NaN,removed to District Court,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,voluntary
3,A. M. Castle & Co.,NaN,NaN,17-11330,NaN,NaN,Steven W. Scheinkman,NaN,Replaced,11,NaN,Wilmington,Wilmington,Wilmington,NaN,yes,Kurtzman Carson Consultants LLC,no,NaN,NaN,NaN,no,NaN,NaN,NaN,no,NaN,NaN,NaN,148411,101,12/31/2016,NaN,NaN,12/31/2016,12/31/2016#https://www.sec.gov/Archives/edgar/data/18172/000001817217000011/0000018172-17-000011-index.htm#,NaN,NaN,12/31/2017,12/31/2017#https://www.sec.gov/Archives/edgar/data/18172/000001817218000007/0000018172-18-000007-index.htm#,12/31/2018,NaN,4/17/2015,1/7/2020,NaN,NaN,8/2/2017,NaN,7/6/2017,5/15/2017,8/2/2017,8/31/2017,8/2/2017,NaN,6/18/2017,1/7/2015,NaN,NaN,NaN,DE,Pachulski Stang,Pachulski Stang Ziehl & Jones LLP,NaN,NaN,"PNC Bank, National Association",NaN,NaN,yes,yes,confirmed,DE,NaN,yes,yes,yes,yes,yes,no,NaN,no,pending,NaN,NaN,Oak Brook,IL Chicago,IL,MD,NaN,NaN,DE,Laurie Selber Silverstein,Laurie Selber Silverstein,NaN,A. M. Castle & Co.,prepackaged,NaN,NaN,not emerged 5,no,NaN,no,no,no,no,Yes,Metals Service Centers and Offices,F: Wholesale Trade,"505 Metals and Minerals, Except Petroleum",50 Wholesale Trade-durable Goods,NaN,Not tort,NaN,NaN,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,voluntary
4,"A123 Systems, Inc.",assets acquired by Wanxiang America Corporation on 1/29/2013,NaN,12-12859,NaN,NaN,David P. Vieau,NaN,Replaced,11,NaN,Wilmington,Wilmington,Wilmington,NaN,yes,"Logan & Company, Inc.",yes,Brown Rudnick,Brown Rudnick LLP / Saul Ewing LLP,NaN,no,NaN,NaN,NaN,no,NaN,NaN,NaN,03739T,108,12/31/2011,NaN,NaN,12/31/2011,12/31/2011#http://edgar.sec.gov/Archives/edgar/data/1167178/000104746912002475/0001047469-12-002475-index.htm#,NaN,NaN,NaN,NaN,NaN,12/11/2012,3/15/2002,1/29/2013,11/2/2012,NaN,5/20/2013,NaN,11/26/2012,2/6/2013,5/20/2013,6/28/2013,12/11/2012,NaN,10/16/2012,1/25/2001,NaN,NaN,NaN,DE,Latham Watkins,"Latham & Watkins LLP / Richards, Layton & Finger, P.A.",NaN,NaN,Johnson Controls Inc.,Wanxiang America Corp.,NaN,yes,yes,confirmed,DE,NaN,yes,yes,yes,yes,no,no,NaN,no,pending,NaN,NaN,Waltham,MA Boston,MA,DE,NaN,NaN,DE; PA ED,Kevin J. Carey,Kevin J. Carey,NaN,A123 Systems LLC,free fall,NaN,NaN,emerged no refile 5,yes,NaN,yes,yes,NaN,"yes, contract",Yes,NaN,D: Manufacturing,"369 Miscellaneous Electrical Machinery, Equipment, and Supplies",36 Electronic And Other Electrical Equipment And Components,NaN,Not tort,NaN,NaN,no,NaN,NaN,NaN,NaN,NaN,none,no turnfirm,none,NaN,none,voluntary
5,"AAC Holdings, Inc.",NaN,NaN,20-11648,NaN,NaN,Andrew W. McWilliams,NaN,Replaced,11,NaN,Wilmington,Wilmington,Wilmington,NaN,yes,"Donlin, Recano & Company, Inc.",yes,Cole Schotz,Cole Schotz PC,NaN,no,NaN,NaN,NaN,no,NaN,NaN,NaN,000307,108,NaN,12/31/2018,NaN,12/31/2018,12/31/2018#https://www.sec.gov/Archives/edgar/data/1606180/000156459019011552/0001564590-19-011552-index.htm#,NaN,NaN,NaN,NaN,NaN,NaN,1/24/2020,2/2/2022,7/2/2020,NaN,10/20/2020,NaN,7/15/2020,9/1/2020,10/20/2020,12/11/2020,10/20/2020,NaN,6/20/2020,6/11/2019,NaN,NaN,NaN,DE,Greenberg Traurig,"Greenberg Traurig, LLP",NaN,NaN,"Ankura Trust Company, LLC, as administrative agent",NaN,NaN,yes,yes,confirmed,DE,NaN,yes,yes,yes,yes,not as of 5/4/2022,NaN,NaN,NaN,pending,NaN,NaN,Brentwood,TN Nashville,TN,NV,NaN,NaN,DE,John T. Dorsey,John T. Dorsey,NaN,"AAC Holdings, Inc.",prenegotiated,NaN,NaN,not emerged 5,no,NaN,no,no,no,maybe,Yes,"Specialty Outpatient Facilities, Not Elsewhere Classified",I: Services,"809 Miscellaneous Health And Allied Services, Not",80 Health Services,NaN,Not tort,NaN,NaN,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,voluntary
6,aaiPharma Inc.,Acquired by Xanodyne in 2005 and operated separately,US00252WAB00,05-11341,NaN,NaN,Ludo J. Reynders,CEO left office in 2010; became CEO of Premier Research Group on 10/29/2010,Replaced,11,NaN,Wilmington,Wilmington,Wilmington,NaN,yes,Bankruptcy Services LLC,yes,Reed Smith,Reed Smith LLP,NaN,denied,NaN,NaN,NaN,no,NaN,NaN,NaN,00252W,104,12/31/2004,NaN,NaN,12/31/2004,12/31/2004#http://edgar.sec.gov/Archives/edgar/data/1013243/000095014405004448/0000950144-05-004448-index.htm#,NaN,NaN,NaN,NaN,NaN,NaN,9/27/2004,7/1/2010,5/24/2005,NaN,1/20/2006,NaN,6/3/2005,12/1/2005,1/20/2006,3/6/2006,1/20/2006,NaN,5/10/2005,10/28/1993,NaN,NaN,3/19/2004,DE,Fried Frank,Fried Frank,NaN,"Rothschild Inc.,","Bank of America, N.A.; Silver Point Finance, LLC",NaN,NaN,yes,yes,confirmed,DE,NaN,yes,yes,yes,yes,no,no,NaN,no,no,continuing 2012-05-14,NaN,Wilmington,NC Wilmington,NC,DE,no,Insider votes not counted 1129(a)(10),DE,Peter J. Walsh,Peter J. Walsh,NaN,aaiPharma Inc.,free fall,No. No 10k for any years,NaN,emerged no refile 5,yes,NaN,no,no,no,no,Yes,Testing Laboratories,I: Services,"873 Research, Development, And Testing Services","87 Engineering, Accounting, Research, Management, and Related Services",subcon,Fraud?,NaN,NaN,no,no,NaN,NaN,no,no,FTI Consulting Inc.,Chief Operating Officer,Greg Rayburn,yes,manage (temps),voluntary
7,"ABC-NACO, Inc.","acquired by Three Cities Research, Inc. and Cerebus",NaN,01-36484,NaN,NaN,Vaugh W. Makary,NaN,Replaced,11,NaN,Chicago,Chicago,Other,NaN,NaN,NaN,yes,Jenner Block,"Jenner & Block, LLC",NaN,no,NaN,NaN,NaN,no,NaN,NaN,NaN,00287P,105,12/31/2000,NaN,NaN,12/31/2000,12/31/2000#http://edgar.sec.gov/Archives/edgar/data/913364/000095013101500730/0000950131-01-500730-index.htm#,NaN,NaN,NaN,NaN,NaN,12/11/2001,4/3/2001,1/14/2002,10/26/2001,NaN,NaN,4/22/2004,11/6/2001,NaN,4/22/2004,NaN,12/11/2001,NaN,10/18/2001,9/16/1987,NaN,NaN,NaN,OT,D'Ancona Pflaum,D'Ancona & Pflaum LLC,NaN,NaN,NaN,NaN,NaN,NaN,yes,dismissed,IL ND,NaN,yes,yes,no,yes,no,no,NaN,no,no,NaN,NaN,Lombard,IL Chicago,IL,DE,NaN,NaN,IL ND,Eugene R. Wedoff,Eugene R. Wedoff,NaN,Meridian Rail Corp.,free fall,NaN,NaN,emerged no refile 5,yes,NaN,yes,yes,no confirmation,maybe,No,NaN,D: Manufacturing,346 Metal Forgings And Stampings,"34 Fabricated Metal Products, Except Machinery and Transportation Equipment",NaN,Not tort,NaN,NaN,no,no,NaN,NaN,no,no,NaN,NaN,NaN,NaN,NaN,voluntary
8,AbitibiBowater Inc.,11/7/2011 name change to Resolute Forest Products,NaN,09-11296,NaN,NaN,David J. Paterson,NaN,Replaced,11,NaN,Wilmington,Wilmington,Wilmington,NaN,yes,"Epiq Bankruptcy Solutions, LLC",yes,Paul Hastings,"Paul, Hastings, Janofsky & Walker LLP",NaN,denied,NaN,NaN,NaN,no,NaN,NaN,NaN,003687,209,12/31/2008,NaN,NaN,12/31/2008,12/31/2008#http://edgar.sec.gov/Archives/edgar/data/1393066/000095014409003734/0000950144-09-003734-index.htm#,12/31/2009,12/31/2009#http://edgar.sec.gov/Archives/edgar/data/1393066/000095012310030866/0000950123-10-030866-index.htm#,12/31/2010,12/31/2010#http://edgar.sec.gov/Archives/edgar/data/1393066/000095012311033041/0000950123-11-033041-index.htm#,12/31/2011,NaN,10/1/2007,1/1/2011,4/28/2009,NaN,11/23/2010,NaN,6/16/2009,8/2/2010,11/23/2010,12/9/2010,11/23/2010,7/14/2009,4/16/2009,1/25/2001,NaN,NaN,5/14/2009,DE,Paul Weiss,"Paul, Weiss, Rifkind, Wharton & Garrison LLP / Young Conaway Stargatt & Taylor, LLP",NaN,Blackstone Advisory Services L.P.,"Fairfax Financial Holdings Ltd. and Avenue Investments, L.P., as Initial Lenders, Law Debenture Trust Company of New York, as administrative agent and Law Debenture Trust Company ofNew York, as collateral agent","Wilmington Trust Company, as pass through trustee, as subordination agent; Deutsche Bank Securities Inc., Morgan Stanley & Co. LLC[ ]purchasers; Deutsche Bank Trust Company Americas, as depositary; MorganStanley Bank, N.A., as [ ] liquidity provider",NaN,yes,yes,confirmed,DE,NaN,yes,yes,yes,yes,yes,no,NaN,yes,fee auditor,continuing 2012-05-14,yes,Montreal,Outside United States,Canada,DE,yes,not on spreadsheet,DE; PA ED,Kevin J. Carey,Kevin J. Carey,NaN,AbitibiBowater Inc.,free fall,NaN,NaN,emerged no refile 5,yes,NaN,yes,no,yes,no,Yes,Paper Mills,D: Manufacturing,262 Paper Mills,26 Paper and Allied Products,no,Not tort,NaN,NaN,no,no,Bowater Canada Finance Corporation,NaN,yes,"Aurelius Capital Management, LP",AlixPartners; Huron Consulting Services LLC,Vice President Restructuring; no office,Lisa J. Donahue; Michael Draa,yes,advise,voluntary
9,Acceptance Insurance Companies Inc.,NaN,NaN,05-80059,NaN,NaN,John E. Martin,End date is the Chapter 7 conversion date,NoReplace,11,NaN,NaN,Omaha,Other,NaN,no,NaN,yes,McGrath North,"McGrath North Mullin & Kratz, PC LLO",NaN,no,NaN,NaN,NaN,no,NaN,NaN,NaN,004308,102,NaN,12/31/2003,NaN,12/31/2003,12/31/2003#http://edgar.sec.gov/Archives/edgar/data/74783/000119312504121962/0001193125-04-121962-index.htm#,NaN,NaN,NaN,NaN,NaN,NaN,12/15/1999,9/7/2010,1/10/2005,NaN,NaN,9/7/2010,NaN,NaN,9/7/2010,NaN,NaN,NaN,1/7/2005,6/28/1985,NaN,NaN,NaN,OT,Kutak Rock,Kutak Rock LLP,NaN,NaN,NaN,NaN,NaN,no,no,converted,NE,NaN,yes,yes,yes,no,no,no,NaN,no,no,liquidation,NaN,Council Bluffs,IA Council Bluffs,IA,DE,NaN,NaN,NE,Timothy J. Mahoney,Timothy J. Mahoney,NaN,not applicable,free fall,NaN,NaN,not emerged 5,no,NaN,no,no,no confirmation,maybe,Yes,"Fire, Marine, And Casualty Insurance","H: Finance, Insurance, And Real Estate","633 Fire, Marine, And Casualty Insurance",63 Insurance Carriers,NaN,Not tort,NaN,NaN,NaN,no,NaN,NaN,no,no,none,no turnfirm,none,no,none,voluntary
10,Accuride Corporation,NaN,US004398AE30,09-13449,NaN,NaN,William M. Lasky,NaN,Replaced,11,NaN,Wilmington,Wilmington,Wilmington,NaN,yes,"The Garden City Group, Inc.",yes,Irell Manella,Irell & Manella LLP,NaN,yes,Sonnenschein Nath,Sonnenschein Nath & Rosenthal LLP,NaN,no,NaN,NaN,NaN,004398,NaN,12/31/2008,NaN,NaN,12/31/2008,12/31/2008#http://edgar.sec.gov/Archives/edgar/data/817979/000110465909017677/0001104659-09-017677-index.htm#,12/31/2009,12/31/2009#http://edgar.sec.gov/Archives/edgar/data/817979/000104746910002892/0001047469-10-002892-index.htm#,12/31/2010,12/31/2010#http://edgar.sec.gov/Archives/edgar/data/817979/000104746911002734/0001047469-11-002734-index.htm#,12/31/2011,NaN,9/22/2008,1/31/2011,10/21/2009,NaN,2/18/2010,NaN,11/2/2009,12/18/2009,2/18/2010,2/26/2010,2/18/2010,NaN,10/8/2009,3/13/2006,NaN,NaN,9/2/2009,DE,Latham Watkins,"Latham & Watkins LLP / Young Conaway Stargatt & Taylor, LLP",NaN,Perella Weinberg Partners LP,Deutsche Bank Trust Company Americas,NaN,NaN,yes,yes,confirmed,DE,NaN,yes,yes,yes,yes,yes,no,NaN,no,no,continuing 2012-05-14,yes,Evansville,IN Evansville,IN,DE,NaN,NaN,DE,Brendan L. Shannon,Brendan L. Shannon,NaN,Accuride Corporation,prenegotiated,NaN,NaN,emerged no refile 5,yes,NaN,yes,no,yes,no,Yes,Motor Vehicle Parts and Accessories,D: Manufacturing,371 Motor Vehicles and Equipment,37 Transportation Equipment,NaN,Not tort,NaN,NaN,no,no,NaN,NaN,no,no,Zolfo Cooper,no office,Scott W. Winn,yes,advise,voluntary
11,Aceto Corporation,NaN,NaN,19-13448,NaN,NaN,William C. Kennally III,Assets sold by 363 sale,NoReplace,11,NaN,Newark,Newark,Other,NaN,yes,Prime Clerk LLC,yes,Stroock Stroock,"Porzio, Bromberg & Newman, PC / Stroock & Stroock & Lavan LLP",NaN,no,NaN,NaN,NaN,no,NaN,NaN,NaN,004446,100,6/30/2018,NaN,NaN,6/30/2018,6/30/2018#https://www.sec.gov/Archives/edgar/data/2034/000114420418051414/0001144204-18-051414-index.htm#,NaN,NaN,NaN,NaN,NaN,4/10/2019,10/2/2017,5/31/2019,2/28/2019,NaN,9/18/2019,NaN,3/15/2019,7/23/2019,9/18/2019,10/1/2019,NaN,NaN,2/19/2019,12/29/2014,NaN,NaN,NaN,OT,Lowenstein Sandler,Lowenstein Sandler LLP,NaN,NaN,Wells Fargo Bank National Association,NaN,NaN,yes,yes,confirmed,NJ,NaN,yes,yes,yes,no,pending,NaN,NaN,NaN,pending,NaN,NaN,Port Washington,NY Central Islip,NY,NY,NaN,NaN,NJ,Vincent F. Papalia,Vincent F. Papalia,NaN,liquidated,free fall,NaN,NaN,not emerged 5,no,NaN,yes,yes,NaN,"yes, buyer",Yes,"Drugs, Drug Proprietaries, And Druggists' Sundries",F: Wholesale Trade,"512 Drugs, Drug Proprietaries, And Druggists' Sundries",51 Wholesale Trade-non-durable Goods,NaN,Not tort,NaN,NaN,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,voluntary
12,"Acme Metals, Incorporated",compact strip process mini-mill sold to International Steel Group Inc. and integrated; 8/2002,NaN,98-02179,NaN,NaN,Stephen D. Bennett,Acquired by International Steel Group on 10/10/2002,NoReplace,11,NaN,Wilmington,Wilmington,Wilmington,NaN,NaN,NaN,yes,NaN,NaN,NaN,denied,NaN,NaN,NaN,no,NaN,NaN,NaN,004724,100,12/28/1997,12/29/1996,12/31/1995,12/28/1997,12/28/1997#http://edgar.sec.gov/Archives/edgar/data/883702/0000950137-98-001025-index.html#,12/27/1998,12/27/1998#http://edgar.sec.gov/Archives/edgar/data/883702/0000950137-99-000380-index.html#,NaN,NaN,NaN,NaN,4/15/1996,10/10/2002,10/14/1998,NaN,11/1/2002,NaN,12/15/1998,8/27/2002,11/1/2002,11/25/2002,NaN,NaN,9/28/1998,10/15/1982,NaN,NaN,NaN,DE,Hughes Hubbard,NaN,"Young, Conaway, Stargatt & Taylor LLP / Hughes Hubbard & Reed LLP",NaN,NaN,NaN,NaN,NaN,yes,confirmed,DE,NaN,yes,docs after date,no,no,no,no,NaN,yes,no,NaN,NaN,Riverdale,IL Chicago,IL,DE,NaN,NaN,OH SD,Randall J. Newsome,NaN,NaN,liquidated,free fall,No. No 10k for 2001 or 2002,NaN,not emerged 5,yes,NaN,no,no,no,no,Yes,"Steel Works, Blast Furnaces (Including Coke Ovens), and Rolling",D: Manufacturing,"331 Steel Works, Blast Furnaces, and Rolling And",33 Primary Metal Industries,NaN,Not tort,NaN,NaN,no,no,NaN,NaN,no,no,NaN,NaN,NaN,NaN,NaN,voluntary
13,"ACT Manufacturing, Inc.",NaN,NaN,01-47641,NaN,NaN,John A. Pino,End date is date sold to Capital Partners Inc.,NoReplace,11,NaN,Worcester,Worcester,Other,NaN,NaN,NaN,yes,Choate Hall,"Choate, Hall & Stewart",NaN,no,NaN,NaN,NaN,no,NaN,NaN,NaN,000973,107,12/31/2000,NaN,NaN,12/31/2000,12/31/2000#http://edgar.sec.gov/Archives/edgar/data/937971/000092701601500106/0000927016-01-500106-index.htm#,NaN,NaN,NaN,NaN,NaN,7/2/2002,1/15/1993,7/17/2002,1/4/2002,NaN,8/13/2003,NaN,NaN,5/12/2003,8/13/2003,NaN,NaN,NaN,12/21/2001,8/10/2000,NaN,NaN,NaN,OT,Mintz Levin,NaN,"Mintz, Levin, Cohn, Ferris, Glovsky and Popeo, PC",NaN,NaN,NaN,NaN,NaN,yes,confirmed,MA,NaN,yes,yes,no,no,no,no,NaN,no,no,NaN,NaN,Hudson,MA Boston,MA,MA,no,"extinguished, substantive consolidation",MA,Joel B. Rosenthal,Joel B. Rosenthal,NaN,liquidated,free fall,No. No 10k for any years,NaN,not emerged 5,yes,NaN,yes,yes,NaN,no,Yes,Printed Circuit Boards,D: Manufacturing,367 Electronic Components And Accessories,36 Electronic And Other Electrical Equipment And Components,subcon,Not tort,NaN,NaN,no,no,NaN,NaN,no,no,NaN,NaN,NaN,NaN,NaN,voluntary